config/routes.rb
Press::Application.routes.draw do

  # Routes for devise users (login logout register..etc)
  devise_for :users, :path => '', :path_names => {
      :sign_in => 'login',
      :sign_out => 'logout',          # must be method :DELETE
      :registration => 'register',    # /register POST
      :sign_up => 'new'               # /register/new
  }

  # Below we define all of our administrator namespace routes.. These are for site admin and site staff members only
  resources :admin, :only => [ :index ]
  namespace :admin do

    # Content Routes
    resources :content do
      collection do
        get :categories, :path => ":id/categories"
      end
    end

    resources :media

    resources :users
    resources :taxonomies
    resources :layouts
    resources :widgets

    # Wordpress import utility
    resources :import_wordpress, :only => [ :new, :create ]

    # Site settings :index for showing the form and :create to post it (though not technically correct)
    resources :settings, :only => [ :index, :create ]
    namespace :settings do
      resources :content, :only => [ :index, :create ]
    end

    # Site tools
    resources :tools, :only => [ :index ]
    namespace :tools do
      resources :software_update, :only => [ :index ] do
        collection do
          get :upgrade, :path => "upgrade"
        end
      end
    end

  end

  # Installation Routes -- #TODO How do we delete this routing entirely after site is installed?
  resources :install, :only => [ :index, :create_owner ] do
    collection do
      post :create_owner, :path => "create_owner"
    end
  end

  # Below I am adding some custom routes to match what wordpress does.
  # I don't know if this is the correct way to add these or not, but they work

  # Category route similar to wordpress
  match '/category/*category' => 'default#category', :as => 'category'
  # Tag route similar to wordpress
  match '/tag/*tag' => 'default#tag', :as => 'tag'
  # Page route which gets us pages deeper into the main index page list, not related to content :pages
  match '/page/*page' => 'default#index', :as => 'page'
  # Default SEO URL (Permalink) route for showing pages and posts
  match '*seo_url' => 'default#show', :as => 'slug'
  # Default
  root :to => 'default#index'

end

app/controllers/install_controller.rb
class InstallController < ApplicationController

  skip_before_filter :installed?

  layout 'install'

  def index
    @user = User.first || User.new
    unless @user.new_record?
      redirect_to admin_settings_path
    end
  end

  def create_owner
    unless User.first.present?
      @user = User.new params[:user]
      @user.role = 'owner'
      if @user.save
        mode = Setting.find_by_key :maintenance
        mode.value = 0
        mode.save

        flash[:success] = 'Site Owner Successfully Created.'
        redirect_to :action => 'index'
      else
        render 'index'
      end
    end
  end

end

app/views/install/_owner_form.html.erb
<fieldset>
  <legend><%=  form_legend  %></legend>

  <div class='control-group<%= " error" if @user.errors.has_key?(:email) %>'>
    <label class='control-label'>Email</label>
    <div class='controls'>
      <%= f.text_field :email, :class => 'input-xlarge' %>
      <% if @user.errors.has_key?(:email) %>
        <span class='help-inline'>Email <%= @user.errors.get(:email).first %></span>
      <% end %>
    </div>
  </div>

  <div class='control-group<%= " error" if @user.errors.has_key?(:password) %>'>
    <label class='control-label'>Password</label>
    <div class='controls'>
      <%= f.password_field :password, :class => 'input-xlarge ' %>
      <% if @user.errors.has_key?(:password) %>
        <span class='help-inline'>Password <%= @user.errors.get(:password).first %></span>
      <% end %>
    </div>
  </div>

  <div class='control-group<%= " error" if @user.errors.has_key?(:password) %>'>
    <label class='control-label'> </label>
    <div class='controls'>
      <%= password_field_tag :password_confirmation, "", { :class => 'input-xlarge ', :placeholder => 'Password Confirmation...' } %>
      <% if @user.errors.has_key?(:password_confirmation) %>
        <span class='help-inline'>Password <%= @user.errors.get(:password_confirmation).first %></span>
      <% end %>
    </div>
  </div>

  <div class='control-group<%= " error" if @user.errors.has_key?(:display_name) %>'>
    <label class='control-label'>Display Name</label>
    <div class='controls'>
      <%= f.text_field :display_name, :class => 'input-xlarge ' %>
      <% if @user.errors.has_key?(:display_name) %>
        <span class='help-inline'>Password <%= @user.errors.get(:display_name).first %></span>
      <% end %>
    </div>
  </div>

  <div class='control-group<%= " error" if @user.errors.has_key?(:first_name) %>'>
    <label class='control-label'>First Name</label>
    <div class='controls'>
      <%= f.text_field :first_name, :class => 'input-xlarge ' %>
      <% if @user.errors.has_key?(:first_name) %>
        <span class='help-inline'>Password <%= @user.errors.get(:first_name).first %></span>
      <% end %>
    </div>
  </div>

  <div class='control-group<%= " error" if @user.errors.has_key?(:last_name) %>'>
    <label class='control-label'>Last Name</label>
    <div class='controls'>
      <%= f.text_field :last_name, :class => 'input-xlarge ' %>
      <% if @user.errors.has_key?(:last_name) %>
        <span class='help-inline'>Password <%= @user.errors.get(:last_name).first %></span>
      <% end %>
    </div>
  </div>

  <div class='form-actions'>
    <%= submit_tag submit_label, :class => 'btn btn-primary' %>
  </div>
</fieldset>

app/views/install/index.html.erb
<div class='row'>
  <div class='span12'>

      <div class='alert alert-info'>
        <strong>Installation -- Site Owner Creation</strong>
        <br />
        Before we can begin we need to create an admin user that you'll use to login and edit things with.  <br />
        Once you have created this user you'll be asked to sign in and forwarded to the settings area.
      </div>

      <%= form_for @user, :url => create_owner_install_index_path, :html => { :class => 'form-horizontal' } do |f| %>

        <%= render :partial => 'owner_form', :locals => {
                :f => f,
                :form_legend => "Create Site Owner",
                :submit_label => "Create Owner"
        } %>

      <% end %>

  </div>
</div>