config/routes.rb
Press::Application.routes.draw do

  # Routes for devise users (login logout register..etc)
  devise_for :users, :path => '', :path_names => {
      :sign_in => 'login',
      :sign_out => 'logout',          # must be method :DELETE
      :registration => 'register',    # /register POST
      :sign_up => 'new'               # /register/new
  }

  # Below we define all of our administrator namespace routes.. These are for site admin and site staff members only
  resources :admin, :only => [ :index ]
  namespace :admin do

    # Content Routes
    resources :content do
      collection do
        get :categories, :path => ":id/categories"
      end
    end

    resources :media

    resources :users
    resources :taxonomies
    resources :layouts
    resources :widgets

    # Wordpress import utility
    resources :import_wordpress, :only => [ :new, :create ]

    # Site settings :index for showing the form and :create to post it (though not technically correct)
    resources :settings, :only => [ :index, :create ]
    namespace :settings do
      resources :content, :only => [ :index, :create ]
    end

    # Site tools
    resources :tools, :only => [ :index ]
    namespace :tools do
      resources :software_update, :only => [ :index ] do
        collection do
          get :upgrade, :path => "upgrade"
        end
      end
    end

  end

  # Installation Routes -- #TODO How do we delete this routing entirely after site is installed?
  resources :install, :only => [ :index, :create_owner ] do
    collection do
      post :create_owner, :path => "create_owner"
    end
  end

  # Below I am adding some custom routes to match what wordpress does.
  # I don't know if this is the correct way to add these or not, but they work

  # Category route similar to wordpress
  match '/category/*category' => 'default#category', :as => 'category'
  # Tag route similar to wordpress
  match '/tag/*tag' => 'default#tag', :as => 'tag'
  # Page route which gets us pages deeper into the main index page list, not related to content :pages
  match '/page/*page' => 'default#index', :as => 'page'
  # Default SEO URL (Permalink) route for showing pages and posts
  match '*seo_url' => 'default#show', :as => 'slug'
  # Default
  root :to => 'default#index'

end

app/controllers/admin/tools/software_update_controller.rb
require 'git-press'
class Admin::Tools::SoftwareUpdateController < AdminController

  def index
    @localVersion = %x{cat VERSION}
    @remoteVersion = Curl::Easy.perform('https://raw.github.com/palamedes/Press/master/VERSION').body_str
  end

  def upgrade
    GitPress.pull
  end

end

app/views/admin/tools/software_update/index.html.erb
<%= breadcrumbs %>

<div class='row'>
  <div class='span12'>

    <% if @localVersion != @remoteVersion %>

      <div class='alert alert-info'>
        <p>It appears there is an update! </p>
        <p>Local version: <%= @localVersion %></p>
        <p>Latest version: <strong><%= @remoteVersion %></strong></p>
      </div>

      <%= link_to upgrade_admin_tools_software_update_index_path %>



    <% else %>

      <div class='alert alert-success'>
        <p><strong>It appears everything is up to date!</strong></p>
        <p>Local & Latest version: <strong><%= @localVersion %></strong></p>
      </div>

    <% end %>

  </div>
</div>