config/routes.rb
Press::Application.routes.draw do

  # Routes for devise users (login logout register..etc)
  devise_for :users, :path => '', :path_names => {
      :sign_in => 'login',
      :sign_out => 'logout',          # must be method :DELETE
      :registration => 'register',    # /register POST
      :sign_up => 'new'               # /register/new
  }

  # Below we define all of our administrator namespace routes.. These are for site admin and site staff members only
  resources :admin, :only => [ :index ]
  namespace :admin do

    # Content Routes
    resources :content do
      collection do
        get :categories, :path => ":id/categories"
      end
    end

    resources :media

    resources :users
    resources :taxonomies
    resources :layouts
    resources :widgets

    # Wordpress import utility
    resources :import_wordpress, :only => [ :new, :create ]

    # Site settings :index for showing the form and :create to post it (though not technically correct)
    resources :settings, :only => [ :index, :create ]
    namespace :settings do
      resources :content, :only => [ :index, :create ]
    end

    # Site tools
    resources :tools, :only => [ :index ]
    namespace :tools do
      resources :software_update, :only => [ :index ] do
        collection do
          get :upgrade, :path => "upgrade"
        end
      end
    end

  end

  # Installation Routes -- #TODO How do we delete this routing entirely after site is installed?
  resources :install, :only => [ :index, :create_owner ] do
    collection do
      post :create_owner, :path => "create_owner"
    end
  end

  # Below I am adding some custom routes to match what wordpress does.
  # I don't know if this is the correct way to add these or not, but they work

  # Category route similar to wordpress
  match '/category/*category' => 'default#category', :as => 'category'
  # Tag route similar to wordpress
  match '/tag/*tag' => 'default#tag', :as => 'tag'
  # Page route which gets us pages deeper into the main index page list, not related to content :pages
  match '/page/*page' => 'default#index', :as => 'page'
  # Default SEO URL (Permalink) route for showing pages and posts
  match '*seo_url' => 'default#show', :as => 'slug'
  # Default
  root :to => 'default#index'

end

app/models/taxonomy.rb
require 'model_helper'

class Taxonomy < ActiveRecord::Base

  # Mass assignable fields
  attr_accessible :name, :seo_url, :description, :classification

  # Add validation
  validates :name,           :presence => true
  validates :seo_url,        :presence => true
  validates :classification, :presence => true

  # A Taxonomy is a keyword (letter, number, word, paragraph, icon..whatever) that is designed to provide some sort
  # of identifier that itself has a classification in order to better organize things.
  # Posts can have many different identifiers such as Tags, and Categories.  More over those taxonomies also reference
  # back to the things they contain.
  has_and_belongs_to_many :contents

  # Before we send to validation, fix the seo_url
  before_validation :preprocess

  # Add validation
  validates :name,    :presence => true
  validates :seo_url, :uniqueness => { :message => "It appears the SEO Url that you entered is already in use" }

  # Backup this sucker on create or update
  after_create :backup, :on => :create
  after_update :backup, :on => :update
  # Purge the backup on destroy
  after_destroy :purge, :on => :destroy
  # Get the original seo_url
  after_initialize do
    self.original_seo_url = self.seo_url
  end
  # This is the old seo_url
  attr_accessor :original_seo_url

  # Define some scoped helpers
  scope :tags, where(:classification => :tag)
  scope :categories, where(:classification => :category)

  # Create a hard backup of this file on the file system (outside of the database)
  # that can be indexed and saved using github or some such repository
  def backup
    if Setting.getValue('backup') && Setting.getValue('backup_location').present?
      File.open("#{Setting.getValue('backup_location')}/taxonomy/#{self.seo_url}.json", 'w+') do |fh|
        fh.write self.to_json
      end
    end
  end

  private

  # Before validation preprocessing
  def preprocess
    self.seo_url = self.name unless self.seo_url.present?
    self.seo_url = ModelHelper::strip_seo_url self.seo_url
  end

  # After all is said and done .. do stuff
  def backup
    ModelHelper::backup self
  end

  # After we have destroyed .. do stuff
  def purge
    ModelHelper::destroy_backup self
  end

end

app/controllers/admin/taxonomies_controller.rb
class Admin::TaxonomiesController < AdminController

  # GET /admin/taxonomies
  # GET /admin/taxonomies.json
  def index
    limit = 10;
    page = (params[:page].to_i - 1) || 1
    @filter = params[:filter] || ''

    @taxonomies = Taxonomy.order('created_at DESC')
    @total_count = @taxonomies.count
    @taxonomies = @taxonomies.where(["name like ? or description like ?", '%'+@filter+'%', '%'+@filter+'%'] ) if @filter.present?
    @filtered_count = @taxonomies.count
    @taxonomies = @taxonomies.limit(limit)
    @taxonomies = @taxonomies.offset(limit.to_i * page.to_i) if page > 0

    @pagination_current_page = (page.to_i + 1) > 0 ? (page.to_i + 1) : 1
    @pagination_number_of_pages = (@filtered_count / limit) +1

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @taxonomies }
    end
  end

  # GET /admin/taxonomies/1
  # GET /admin/taxonomies/1.json
  def show
    @taxonomy = Taxonomy.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @taxonomy }
    end
  end

  # GET /admin/taxonomies/new
  # GET /admin/taxonomies/new.json
  def new
    @taxonomy = Taxonomy.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @taxonomy }
    end
  end

  # GET /admin/taxonomies/1/edit
  def edit
    @taxonomy = Taxonomy.find(params[:id])
  end

  # POST /admin/taxonomies
  # POST /admin/taxonomies.json
  def create
    @taxonomy = Taxonomy.new(params[:taxonomy])

    respond_to do |format|
      if @taxonomy.save
        format.html { redirect_to admin_taxonomies_path, notice: 'Taxonomy was successfully created.' }
        format.json { render json: @taxonomy, status: :created }
      else
        format.html { render action: "new" }
        format.json { render json: @taxonomy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/taxonomies/1
  # PUT /admin/taxonomies/1.json
  def update
    @taxonomy = Taxonomy.find(params[:id])

    respond_to do |format|
      if @taxonomy.update_attributes(params[:taxonomy])
        format.html { redirect_to admin_taxonomies_path, notice: 'Taxonomy was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @taxonomy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/taxonomies/1
  # DELETE /admin/taxonomies/1.json
  def destroy
    @taxonomy = Taxonomy.find(params[:id])
    @taxonomy.destroy

    respond_to do |format|
      format.html { redirect_to admin_taxonomies_url }
      format.json { head :no_content }
    end
  end
end

app/views/admin/taxonomies/_categories_form.html.erb
<% Taxonomy.categories.each do |category| %>
  <% if @content.present? %>
    <label class='checkbox'><%= check_box_tag "taxonomies[]", "#{category.id}", @content.has_taxonomy?(category.id) %><%= category.name %></label>
  <% else %>
    <label class='checkbox'><%= check_box_tag "taxonomies[]", "#{category.id}", false %><%= category.name %></label>
  <% end %>
<% end %>

app/views/admin/taxonomies/_category_modal.html.erb
<div id='category-modal' class='modal hide fade in'>
  <%= form_for category, :url => admin_taxonomies_path(category), :remote => true, :html => { :'data-type' => 'json', :class => 'form-horizontal', :id => 'category_modal' } do |f| %>
    <%= hidden_field_tag "taxonomy[classification]", :category %>
    <div class='modal-header'>
      <a class="close" data-dismiss='modal'>&times;</a>
      <h3>New Category</h3>
    </div>
    <div class='modal-body'>
      <fieldset>

        <div class='control-group'>
          <label class='control-label'>Name</label>
          <div class='controls'>
            <%= f.text_field :name, :class => 'input-xlarge' %>
            <span class='help-inline'></span>
          </div>
        </div>

        <div class='control-group'>
          <label class='control-label'>SEO Url</label>
          <div class='controls'>
            <%= f.text_field :seo_url, :class => 'input-xlarge' %>
            <span class='help-inline'></span>
          </div>
        </div>

        <div class='control-group'>
          <label class='control-label'>Description</label>
          <div class='controls'>
            <%= f.text_area :description, :size => '50x8', :class => 'input-xlarge' %>
            <span class='help-inline'></span>
          </div>
        </div>

      </fieldset>
    </div>
    <div class='modal-footer'>
      <a href="#" class='btn btn-primary submit' data-partial-url='<%= categories_admin_content_index_path((@content.id || 0)) %>'>Submit</a>
      <a href="#" class='btn' data-dismiss='modal'>Close</a>
    </div>
  <% end %>
</div>

app/views/admin/taxonomies/_form.html.erb
<fieldset>
  <div class='span9'>

    <h6>Taxonomy Display Name</h6>
    <div class='control-group<%= " error" if @taxonomy.errors.has_key?(:name) %>'>
      <div class='controls'>
        <%= f.text_field :name, :class => 'span9' %>
        <% if @taxonomy.errors.has_key?(:name) %>
          <span class='help-inline'>Name <%= @taxonomy.errors.get(:name).first %></span>
        <% end %>
      </div>
    </div>

    <h6>Description</h6>
    <div class='control-group<%= " error" if @taxonomy.errors.has_key?(:description) %>'>
      <div class='controls'>
        <%= f.text_area :description, :size => '50x3', :class => 'span9' %>
        <% if @taxonomy.errors.has_key?(:description) %>
          <span class='help-inline'>Description <%= @taxonomy.errors.get(:description).first %></span>
        <% end %>
      </div>
    </div>

  </div>
  <div class='span3'>

    <h6>SEO Url
      <a href="#"><i class="icons-tiny-help"></i></a>
    </h6>
    <div class='control-group<%= " error" if @taxonomy.errors.has_key?(:seo_url) %>'>
      <div class='controls'>
        <%= f.text_field :seo_url, :class => 'span3', :placeholder => "SEO Url" %>
        <% if @taxonomy.errors.has_key?(:seo_url) %>
          <span class='help-inline'>SEO Url <%= @taxonomy.errors.get(:seo_url).first %></span>
        <% end %>
      </div>
    </div>

    <h6>Classification</h6>
    <div class='control-group<%= " error" if @taxonomy.errors.has_key?(:classification) %>'>
      <div class='controls'>
        <%= select_tag('taxonomy[classification]', options_for_select([
                ['Tag', :tag],
                ['Category', :category]
        ], @taxonomy.classification), :class => 'span3') %>
        <% if @taxonomy.errors.has_key?(:classification) %>
          <span class='help-inline'>Classification <%= @taxonomy.errors.get(:classification).first %></span>
        <% end %>
      </div>
    </div>

  </div>
</fieldset>

app/views/admin/taxonomies/edit.html.erb
<%= form_for [:admin, @taxonomy], :html => { :class => '' } do |f| %>

  <%= breadcrumbs :right_items => [
          submit_tag("Update Taxonomy", :class => 'btn btn-primary btn-mini'),
          link_to("Cancel", admin_taxonomies_path, :class => 'btn btn-mini')
  ] %>

  <div class='row'>
    <%= render :partial => 'form', :locals => { :f => f } %>
  </div>

<% end %>

app/views/admin/taxonomies/index.html.erb
<%= breadcrumbs :right_items => [
        link_to(new_admin_taxonomy_path, :class => 'btn btn-primary btn-mini') {
          "<i class='icon-plus icon-white'></i> Add New Taxonomy".html_safe
        }
]%>

<div class='row'>
  <div class='span12'>

    <table class='table table-striped'>
      <thead>
      <tr>
        <th><%= check_box_tag "all-posts" %></th>
        <th>Title</th>
        <th>Slug</th>
        <th>Description</th>
        <th>Type</th>
        <th class='span2 center'>Actions</th>
      </tr>
      </thead>
      <tbody>
      <% @taxonomies.each do |taxonomy| %>
        <tr>
          <td><%= check_box_tag "taxonomies[#{taxonomy.id}]" %></td>
          <td><%= taxonomy.name %></td>
          <td><%= taxonomy.seo_url %></td>
          <td><%= taxonomy.description %></td>
          <td><%= taxonomy.classification.capitalize %></td>
          <td class='span2 center'>
            <%= link_to 'Edit', edit_admin_taxonomy_path(taxonomy), :class => 'btn btn-mini' %>
            <%= link_to 'Destroy', admin_taxonomy_path(taxonomy), confirm: "You've chosen to delete this taxonomy. Are you sure?", method: :delete, :class => 'btn btn-mini btn-danger' %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>

    <div class="btn-toolbar">

      <%= pagination %>

    </div>

  </div>
</div>

app/views/admin/taxonomies/new.html.erb
<%= form_for [:admin, @taxonomy], :html => { :class => '' } do |f| %>

  <%= breadcrumbs :right_items => [
        submit_tag("Create Taxonomy", :class => 'btn btn-primary btn-mini'),
        link_to("Cancel", admin_taxonomies_path, :class => 'btn btn-mini')
  ] %>

  <div class='row'>
      <%= render :partial => 'form', :locals => { :f => f } %>
  </div>

<% end %>